steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/v-dify-backend:$COMMIT_SHA', '.']
    dir: 'api'

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/v-dify-backend:$COMMIT_SHA']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy v-dify-backend \
          --image gcr.io/$PROJECT_ID/v-dify-backend:$COMMIT_SHA \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated

images:
  - 'gcr.io/$PROJECT_ID/v-dify-backend:$COMMIT_SHA'

substitutions:
  _COMMIT_SHA: $COMMIT_SHA
